apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: fivetran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: fivetran
spec:
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 31433
  type: NodePort
